# Generated by Django 5.0.2 on 2024-03-17 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EMPLOYEE_LOGIN',
            fields=[
                ('EMP_DIG_ID', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('EMP_PNO', models.CharField(max_length=5)),
                ('EMP_NAME', models.CharField(max_length=50)),
                ('EMP_DESIGNATION', models.CharField(max_length=25)),
                ('EMP_DEPTT', models.CharField(max_length=25)),
                ('EMP_PASSWORD', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='EMP_ATTENDANCE_REC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMP_CHECKIN_DATETIME', models.DateTimeField()),
                ('EMP_CHECKOUT_DATETIME', models.DateTimeField()),
                ('EMP_DIG_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.employee_login')),
            ],
        ),
    ]
