# Generated by Django 5.0.2 on 2024-03-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_attendance_rec',
            name='EMP_CHECKOUT_DATETIME',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
